addons:
  sonarcloud:
    organization: akadir-github
    token:
      secure: "mGvaxJfLNgPfP0LUD7hN8qoQZHu2w+DhzLtmbmnogLq9x8Cd4JZne7WDxXyFZKXMJOUoxk4FltT81rj2myUVwkaQqp6NVozYQhAP5QzDrFoP0XfHhbQHX314oi4sgacLg5sxxpRf/gSxN9kEzKwfdQhw0Hz3Cdzlu0UYA6iISRMQXV4QQRdu2jICNLAVO/xgysS3OsAKhb6jdIpry1JKESgLQGWMo6jWidM0L3Pvs2pdeh9hZQInA30LZx7ecCzLODVmYVzFt+WkeukeO20CgxslQTpXfj3OIiA1XO5MBUYs3Mdo+JPtHR74R6nK2FK0YRkXAplFD0J1rY1B20AezdGydsUt46iLRckmM1v7fcgpGztznGbLHrXZ/WPjToPg46hAQ4DCW4iQdG/1H3ZJP1Jd0yxUMw0ew39jn5T7lbzgXVBRsSCZYjC6XGyBjHNiehbHM58F00L3VUolbPtyATLnS1r6G6vtps4ZyAnG1knU4NoflJL6Lg6jo9qUNCnCT+qYTwr/muw6VNqOZHB2jNVZtq4UOVaNs2uAiHNQzuG+wVnIxtkf5WxLoJ0TjKAPRDVVWwZjuKema16q3EkAntCQVD3snsQ1yFjgoVmGcRbCxnEFX984A0aSHfOtJV7tLO55n6HoPM1W2dFTqbDzweDmavptDGQMDYSG3D30TIw="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
