addons:
  sonarcloud:
    organization: default
    token:
      secure: "fn2xIuzHd2TJ1RCFTLJ9zoDPR4NGqoTl2tOrZkMe5vBtQYRR6rFhrh2Uj3Lx8IMmFQumBm0pjAqZDpSmoIT7eVoQeAQiUENJIMnNrI7btOa1ZfPDY6QsGf4x9j4KL5SREe4lio45TINJWns/82d/T/tU4MQURIK3QC4myFF8Ff0gi19PtS8jYOZj15pILEcv7+bjwYlAehM0QWJJrjyb5n27G9uyfGhmlB+GXgsLgaxh+Sc/NriCLkGYizm4uQVlJPTdh/NiADTgHswz938ukXlbYbKPiS2RuOKawPTtAtSltX2rw7Q6iTZxN3a3zav4q4QQEbwStEkzVWpPlQ09JkMiJPyDmRqJ1akfQruLHV3RRMN7Jbynb1pslNV/ODVCwKnQlCkJ3VaQqkB0M0/WUY3NJdRUwADNv1a8wHYu6jp1ZZNwSImpsLCe+djyAXbkGootdJYySMURuTCawGVYqODs7ZN60R4dzI4rK4tcSFVw2TFeKBtSfvNHdHnzNOwM+bAjWpoH1o5vXjc0QNLZuQ9RY4HpbVqk0tvX8aa+IPVOSgFrTV06rHtlzS5qcpQSCHdv9hPz1GbZIiNQPHlGShn6G8t5RkneSiHJWdlp7tB0+X2MzV/f8M9FHmohG8S6IBLyV2WcAcxfr3V1fKM+KxA0Av4QjfB3kfOLixG7J/Q="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
