addons:
  sonarcloud:
    organization: akadir
    token:
      secure: "fTn0S8f9V8XU/nD8xGGbqEBdKKf3XmUYa45ktrwmMVNax2/TRiu7P2q4Oum6Xa3V0S2IyOlIIXPCAegf9anX8l43X/v7UsK0pFVAeuLeTMR4k1rhak/df8BxMhuSrOXThW4CN9bFpmcQMyTIc+r3pd/oyTUOarXorJsc1NgMeDCHPbE+S3JW88KmM8HCrzb+hlanZBO9YUvi4OaRW6/cUpqEiWXHAEMqhqb/i40XVS+pZQR3lfNTssX50gjUeyhLad0NNkMK5jwr0A1bMKlHszUh6QxFWG/9AmKig9vU5WyCe54wjCLNinf4r54C9I8oLO3UyOuBMKRbwoqXM6ZUYfAxa47jBKcc4acsF2FmBfpIgYQMwUQu+ll6BlgHi+hN7WtXDg66BZvcZWcXdJjRxDl4yUPEwRT8heUx4O6JA2W3x0dYtT5gFI8kgzos2pa6bvuPES2IeMeX0FaGldxO70WTwV5buC7+WmNCp2QEev/2ZtU5oi0UoU3VCCDqU0seKeNjf8qMI/NgcAQdiuH9L68f3SKJaiqAa4EfSQsga72ojiGDGFNFyt1oKSyi8SarG8WWSq4cVCGqMtoiUQLUa6KrjJWLT1+I9qJb4uLbkh9r4P1UX3oHzLW0j0qsyADatzH79OR7tsb2pVRqGlc4KB6+OErZY7wAtuPdfJ2s5Hs="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
