addons:
  sonarcloud:
    organization: akadir
    token:
      secure: "L7S2TQL4gORJ4/d4Q0sJkK0GCKfJiIQtdNCWMaE6Q9d10c9K2jKPLQugxF/NoMg9MlMSKTgjh0hqp6yvsq08jZSrUpNlcaObkClOjPN+7o1uWXJvPxKrEKqcCG1j+BH7jXsJfYj2mz3kqNhTXIJTPKnPv5nFizzEIosNFjgI4ExgyVqYaWF97iur5LnKYp4GvsTJlUfDIFJpAdQ7iR2OPXXgc4FmDzj7JR0aq+NDUD6aMwMajYaApXO0IrdiJ5YlaBXF5tYfUpZN5FfC+DP9eCyNnbqXm/b4eOFoeH3RhkgUtAdTEInZtiaOKqbr5HFmgb23YeDseaCck5kCit39lB9WzhATM0YHn6a0Vb+P79t3XDkhbfXeL1eoaxfbUpDIxf8edCkFEvWENuOzIPhsyuYnP3yB0Qa4Bp4h8IIL/lLG50ltQk3blUb4C7w8Ina6U4wmA217uWbwGyqEy3PSL0GZN/1J/1j+rw6HLvMHJUezjS99h6M+e2yGZ+2OR0r3ddnk21RrtFQOwXY/Txv0jZFA7YYcEgA+/sWZWIpIN2IzVDVgUN4dN4FzBswOqHYJWPOviGlvNB9OG8Prd70IuomkHaB8IWfEWJ52UZK+g5TtQM+xbRQSePinkcK5xgQwMI1h2Ad8v37ioQcqYwyfjrOURrOBclg+yiO6bxaeVHs="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
